// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_logs.sql

package dao

import (
	"context"
	"time"
)

const countUserLogsByUserID = `-- name: CountUserLogsByUserID :one
SELECT COUNT(*) FROM user_logs WHERE user_id = $1
`

func (q *Queries) CountUserLogsByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserLogsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserLog = `-- name: CreateUserLog :exec
INSERT INTO user_logs (id, user_id, action, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateUserLogParams struct {
	ID        string    `db:"id" json:"id"`
	UserID    string    `db:"user_id" json:"user_id"`
	Action    string    `db:"action" json:"action"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateUserLog(ctx context.Context, arg CreateUserLogParams) error {
	_, err := q.db.ExecContext(ctx, createUserLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.CreatedAt,
	)
	return err
}

const getUserLogsByUserID = `-- name: GetUserLogsByUserID :many
SELECT id, user_id, action, created_at
FROM user_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserLogsByUserIDParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetUserLogsByUserID(ctx context.Context, arg GetUserLogsByUserIDParams) ([]UserLog, error) {
	rows, err := q.db.QueryContext(ctx, getUserLogsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserLog{}
	for rows.Next() {
		var i UserLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
