version: '3'

vars:
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: app_db

tasks:
  default:
    desc: ヘルプを表示
    cmds:
      - task --list

  # Podman関連
  podman:up:
    desc: Podmanコンテナを起動
    cmds:
      - podman-compose up

  podman:down:
    desc: Podmanコンテナを停止
    cmds:
      - podman-compose down

  podman:logs:
    desc: Podmanログを表示
    cmds:
      - podman-compose logs -f

  podman:ps:
    desc: Podmanコンテナの状態を表示
    cmds:
      - podman-compose ps

  podman:restart:
    desc: Podmanコンテナを再起動
    cmds:
      - podman-compose restart

  # データベース関連
  db:migrate:
    desc: psqldefを使用してデータベースマイグレーションを実行
    cmds:
      - psqldef -U {{.DB_USER}} -p {{.DB_PORT}} -h {{.DB_HOST}} {{.DB_NAME}} --password={{.DB_PASSWORD}} --file=db/schema/schema.sql

  db:dry-run:
    desc: データベースマイグレーションのドライラン
    cmds:
      - psqldef -U {{.DB_USER}} -p {{.DB_PORT}} -h {{.DB_HOST}} {{.DB_NAME}} --password={{.DB_PASSWORD}} --file=db/schema/schema.sql --dry-run

  db:export:
    desc: 現在のDBスキーマをエクスポート
    cmds:
      - echo "Exporting current database schema..."
      - psqldef -U {{.DB_USER}} -p {{.DB_PORT}} -h {{.DB_HOST}} {{.DB_NAME}} --password={{.DB_PASSWORD}} --export

  db:generate-migration:
    desc: スキーマ変更からマイグレーションファイルを生成
    cmds:
      - |
        if [ -z "{{.NAME}}" ]; then
          echo "Error: NAME is required. Usage: task db:generate-migration NAME=add_user_status"
          exit 1
        fi
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        FILENAME="db/migrations/${TIMESTAMP}_{{.NAME}}.sql"
        psqldef -U {{.DB_USER}} -p {{.DB_PORT}} -h {{.DB_HOST}} {{.DB_NAME}} --password={{.DB_PASSWORD}} --file=db/schema/schema.sql --dry-run > ${FILENAME}
        if [ -s ${FILENAME} ]; then
          echo "Migration file created: ${FILENAME}"
          cat ${FILENAME}
        else
          echo "No schema changes detected. Removing empty file."
          rm ${FILENAME}
        fi

  # 開発サーバー関連
  dev:
    desc: バックエンド開発サーバーをAirで起動（ホットリロード対応）
    cmds:
      - air

  run:backend:
    desc: バックエンドサーバーを起動（通常起動、ホットリロードなし）
    cmds:
      - go run cmd/server/main.go

  # コード生成関連
  generate:dao:
    desc: DAOコードをsqlcで生成
    cmds:
      - sqlc generate

  generate:openapi:
    desc: TypeSpecからOpenAPI YAMLを生成
    cmds:
      - pnpm exec tsp compile typespec/main.tsp --output-dir openapi

  generate:api:
    desc: OpenAPI仕様からGoのサーバーコードを生成
    cmds:
      - mkdir -p pkg/generated/openapi
      - |
        if command -v oapi-codegen >/dev/null 2>&1; then
          oapi-codegen -generate types,chi-server -package openapi -o pkg/generated/openapi/server.gen.go openapi/openapi.yaml
        else
          $(go env GOPATH)/bin/oapi-codegen -generate types,chi-server -package openapi -o pkg/generated/openapi/server.gen.go openapi/openapi.yaml
        fi

  generate:
    desc: すべてのコード生成を実行（TypeSpec → OpenAPI → Go + DAO）
    cmds:
      - task: generate:openapi
      - task: generate:api
      - task: generate:dao

  # ビルド関連
  build:
    desc: バックエンドをビルド
    cmds:
      - go build -o bin/server cmd/server/main.go

  # クリーンアップ
  clean:
    desc: ビルド成果物を削除
    cmds:
      - rm -rf bin/
      - rm -rf tmp/
      - rm -rf web/dist/
      - rm -rf web/src/api/generated/
      - rm -rf internal/infrastructure/dao/
      - rm -rf web/coverage/
      - rm -f coverage.out
      - rm -f build-errors.log

  # テスト関連
  test:
    desc: バックエンドのテストを実行
    cmds:
      - go test -v -race ./...

  test:coverage:
    desc: カバレッジ付きでテストを実行
    cmds:
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

  # リント・フォーマット関連
  lint:
    desc: golangci-lintを実行
    cmds:
      - cmd: 'which golangci-lint > /dev/null || (echo "golangci-lintがインストールされていません。インストール: https://golangci-lint.run/welcome/install/" && exit 1)'
      - golangci-lint run --timeout=5m

  fmt:
    desc: gofmtとgoimportsでコードをフォーマット
    cmds:
      - gofmt -s -w .
      - goimports -w .

  vet:
    desc: go vetを実行
    cmds:
      - go vet ./...

  check:fmt:
    desc: フォーマットチェック（CI用）
    cmds:
      - |
        if [ -n "$(gofmt -l .)" ]; then
          echo "以下のファイルがgofmtでフォーマットされていません:"
          gofmt -l .
          exit 1
        fi

  check:imports:
    desc: goimportsチェック（CI用）
    cmds:
      - |
        if [ -n "$(goimports -l .)" ]; then
          echo "以下のファイルがgoimportsでフォーマットされていません:"
          goimports -l .
          exit 1
        fi

  modernize:
    desc: modernize analyzerでコードを自動修正
    cmds:
      - echo "modernize analyzerを実行してコードを現代化します..."
      - modernize -fix -test ./...

  modernize:check:
    desc: modernize analyzerでチェックのみ実行
    cmds:
      - echo "modernize analyzerでチェック中..."
      - modernize ./...

  # CI関連
  ci:test:
    desc: CI用のすべてのチェックを実行
    deps: [lint, vet, check:fmt, check:imports, modernize:check, test]
    cmds:
      - echo "すべてのチェックが完了しました"

  # 開発フロー全体
  dev:all:
    desc: 開発環境を一括起動（DB + バックエンド）
    cmds:
      - echo "開発環境の起動手順："
      - echo "  1. task podman:up      # PostgreSQLを起動"
      - echo "  2. task db:migrate     # データベースマイグレーション"
      - echo "  3. task dev            # バックエンドを起動（別ターミナル）"
      - echo ""
      - echo "または並列実行："
      - echo "  task podman:up && task db:migrate"
      - echo "  # 別ターミナルで: task dev"
